#!/usr/bin/env python3
"""Deterministic generator for community/COMMUNITY_IMPACT.md from impact.json.

Usage:
  python3 community/generate_impact.py          # write COMMUNITY_IMPACT.md
  python3 community/generate_impact.py --check  # exit 1 if Markdown is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "community" / "impact.json"
MD_PATH = ROOT / "community" / "COMMUNITY_IMPACT.md"
SCHEMA_PATH = ROOT / "community" / "impact.schema.json"

# Sort keys for stable record ordering.
SORT_KEYS = ("date", "impact_id")


def load_records() -> list[dict]:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit("impact.json must be a top-level JSON array")
    return sorted(
        data,
        key=lambda r: tuple(r.get(k) or "" for k in SORT_KEYS),
    )


def render(records: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Community impact")
    lines.append("")
    lines.append(
        "Adoptions, contributor discoveries and independently verifiable outcomes."
    )
    lines.append(
        "This file is generated by `community/generate_impact.py` from "
        "`community/impact.json`. Do not hand-edit this file as authority; "
        "edit the JSON and re-run the generator."
    )
    lines.append("")
    lines.append(
        "| impact_id | date | type | person_or_project | contributors | evidence | source_state | source |"
    )
    lines.append("|---|---|---|---|---|---|---|---|")
    for r in records:
        contrib = ", ".join(r.get("contributors") or []) or "-"
        lines.append(
            "| `{id}` | {date} | {typ} | {pop} | {contrib} | {ev} | {ss} | {src} |".format(
                id=r["impact_id"],
                date=r["date"],
                typ=r["type"],
                pop=r["person_or_project"],
                contrib=contrib,
                ev=r["evidence_status"],
                ss=r.get("source_state", ""),
                src=r["public_source"],
            )
        )
    lines.append("")
    lines.append("## Records")
    lines.append("")
    for r in records:
        lines.append(f"### {r['impact_id']}")
        lines.append("")
        lines.append(f"- **Type:** {r['type']}")
        lines.append(f"- **Person/project:** {r['person_or_project']}")
        if r.get("contributors"):
            lines.append(
                "- **Contributors:** " + ", ".join(r["contributors"])
            )
        if r.get("maintainers"):
            lines.append(
                "- **Maintainers:** " + ", ".join(r["maintainers"])
            )
        if r.get("credit_statement"):
            lines.append(f"- **Credit:** {r['credit_statement']}")
        lines.append(f"- **Summary:** {r['summary']}")
        lines.append(f"- **Minefield role:** {r['minefield_role']}")
        lines.append(f"- **Evidence:** {r['evidence_status']}")
        if r.get("wording_guardrail"):
            lines.append(f"- **Guardrail:** {r['wording_guardrail']}")
        lines.append(f"- **Follow-up:** {r['follow_up_state']}")
        lines.append(f"- **Source state:** {r.get('source_state')}")
        lines.append(
            f"- **Source state reason:** {r.get('source_state_reason')}"
        )
        lines.append(f"- **Last verified:** {r['last_verified']}")
        lines.append(f"- **Public source:** {r['public_source']}")
        lines.append("")
    # Trailing newline only - no generation timestamp (deterministic).
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if COMMUNITY_IMPACT.md does not match generated output",
    )
    args = ap.parse_args(argv)
    records = load_records()
    text = render(records)
    if args.check:
        if not MD_PATH.exists():
            print("FAIL: COMMUNITY_IMPACT.md missing", file=sys.stderr)
            return 1
        current = MD_PATH.read_text(encoding="utf-8")
        if current != text:
            print(
                "FAIL: community/COMMUNITY_IMPACT.md is stale; "
                "run community/generate_impact.py",
                file=sys.stderr,
            )
            return 1
        print("OK community/COMMUNITY_IMPACT.md is current")
        return 0
    MD_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {MD_PATH.relative_to(ROOT)} ({len(records)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
